import { suggestFiveYearEstimate } from "./defaults";
import type { ForPackage, RenderedSection, SectionId } from "./types";

function money(n: number | null | undefined): string {
  if (n == null || Number.isNaN(n)) return "[amount TBD]";
  return n.toLocaleString("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 });
}

function num(n: number | null | undefined, fallback = "[TBD]"): string {
  if (n == null || Number.isNaN(n)) return fallback;
  return String(n);
}

function esc(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function mdToSimpleHtml(md: string): string {
  const lines = md.split("\n");
  const out: string[] = [];
  let inList = false;
  for (const line of lines) {
    if (line.startsWith("# ")) {
      if (inList) {
        out.push("</ul>");
        inList = false;
      }
      out.push(`<h1>${esc(line.slice(2))}</h1>`);
    } else if (line.startsWith("## ")) {
      if (inList) {
        out.push("</ul>");
        inList = false;
      }
      out.push(`<h2>${esc(line.slice(3))}</h2>`);
    } else if (line.startsWith("### ")) {
      if (inList) {
        out.push("</ul>");
        inList = false;
      }
      out.push(`<h3>${esc(line.slice(4))}</h3>`);
    } else if (line.startsWith("- ")) {
      if (!inList) {
        out.push("<ul>");
        inList = true;
      }
      out.push(`<li>${esc(line.slice(2))}</li>`);
    } else if (line.trim() === "") {
      if (inList) {
        out.push("</ul>");
        inList = false;
      }
      out.push("");
    } else {
      if (inList) {
        out.push("</ul>");
        inList = false;
      }
      out.push(`<p>${esc(line)}</p>`);
    }
  }
  if (inList) out.push("</ul>");
  return out.join("\n");
}

function section(id: SectionId, title: string, markdown: string): RenderedSection {
  return { id, title, markdown, html: mdToSimpleHtml(markdown) };
}

function is24x7Text(v: ForPackage["ops"]["is24x7"]): string {
  switch (v) {
    case "yes":
      return "is answering 9-1-1 calls around the clock.";
    case "no_grandfathered":
      return "is not answering 9-1-1 calls 24/7, but it was assured of CA 9-1-1 Branch funding prior to the establishment of this standard.";
    case "no_plan":
      return "is not answering 9-1-1 calls 24/7 and a plan is being developed to answer 9-1-1 calls on a 24/7 basis.";
    case "no_funding_risk":
      return "is not answering 9-1-1 calls 24/7 and the PSAP management has been advised that funding from the CA 9-1-1 Branch will cease unless the PSAP is willing to accept 9-1-1 calls on a 24/7 basis.";
    default:
      return "24/7 posture requires confirmation during the FOR meeting.";
  }
}

function text911Text(v: ForPackage["ops"]["textTo911"]): string {
  switch (v) {
    case "ott":
      return "This PSAP is currently using an Over-the-Top (OTT) text-to-911 solution and should have personnel logged in 24/7 and available to receive and respond to text-to-911 messages.";
    case "integrated":
      return "This PSAP has text-to-911 integrated into the CPE solution and should have personnel logged into a terminal capable of receiving and responding to text-to-911 messages.";
    default:
      return "Text-to-911 deployment posture (OTT vs CPE-integrated) should be confirmed during the FOR meeting. Per California Government Code section 53112(d), each PSAP shall deploy text-to-911 capability.";
  }
}

export function renderCover(pkg: ForPackage): RenderedSection {
  const c = pkg.cover;
  const md = `# Fiscal and Operational Review — Cover

**State of California**  
**9-1-1 Emergency Communications Branch**

## ${c.psapName || "[PSAP Name]"}

**Date of FOR:** ${c.forDate || "[Date]"}

| Field | Value |
| --- | --- |
| PSAP Manager | ${c.managerName || "[TBD]"} |
| PSAP Address | ${c.address || "[TBD]"} |
| PSAP Phone | ${c.phone || "[TBD]"} |
| Advisor | ${c.advisorName || "[TBD]"} |
| Advisor Phone | ${c.advisorPhone || "[TBD]"} |

Prepared by ${c.advisorName || "[Advisor]"}, 9-1-1 Advisor, Advisory & Compliance Unit  
State of California — 9-1-1 Emergency Communications Branch

*Draft package generated by FOR Assembly Engine ${pkg.meta.version}. Decision support only.*
`;
  return section("cover", "Cover Page", md);
}

export function renderSectionI(pkg: ForPackage): RenderedSection {
  const f = pkg.fiscal;
  const five = suggestFiveYearEstimate(pkg);
  const md = `# Section I — Fiscal Review

**PSAP:** ${pkg.cover.psapName || "[PSAP Name]"}  
**Date:** ${pkg.cover.forDate || "[Date]"}

The following Fiscal and Operational Review (FOR) provides the Public Safety Answering Point (PSAP) with summary information about the California 9-1-1 Emergency Communications Branch (CA 9-1-1 Branch) funding that has been provided.

## 1. Customer Premise Equipment (CPE) Replacement/Upgrade and Maintenance Costs

This information summarizes the total expenses reimbursed for the last replacement or upgrade of the CPE at the PSAP, including residual spending (if applicable) and the costs associated with maintenance for that system.

- **CPE / last upgrade (CPE-only cost entered):** ${money(f.cpeOnlyCost)}

## 2. Annual Training Allotment (ATA) Reimbursements

The CA 9-1-1 Branch allots a specific dollar amount to each PSAP to cover expenses for specifically defined 9-1-1 related training held within the State of California within that fiscal year.

- **ATA funding level:** ${f.ataLevel || "[TBD]"}
- **ATA balance remaining (current FY):** ${money(f.ataBalance)}

## 3. Estimated Recurring / Ongoing Costs Paid by the CA 9-1-1 Branch

- **Ongoing operations (past FY / recurring estimate):** ${money(f.ongoingOpsCost)}
- **Authorized reimbursements (past FY, excl. ATA/CPE where separated):** ${money(f.reimbursementsPastFy)}
- **Foreign language emergency interpretation:** ${money(f.foreignLanguageCost)}
- **MIS / ECaTS note:** ${f.misCostNote || "[see Branch guidance]"}

## 4. Five-year estimate

The CA 9-1-1 Branch anticipates providing approximately **${money(five)}** over five years for 9-1-1 service at ${pkg.cover.psapName || "[PSAP]"} (estimate; Advisor may adjust for one-time network initiation or unique circumstances per prep instructions).

${f.fiscalNotes ? `## Notes\n\n${f.fiscalNotes}` : ""}

*Include in binder: Summary worksheet figures and Foreign Language report when available. Other fiscal tabs depend on discussion areas.*
`;
  return section("section_i", "Section I — Fiscal Review", md);
}

export function renderSectionII(pkg: ForPackage): RenderedSection {
  const n = pkg.network;
  const md = `# Section II — Network Review

**PSAP:** ${pkg.cover.psapName || "[PSAP Name]"}  
**Date:** ${pkg.cover.forDate || "[Date]"}

The Network Review addresses the specific network services provisioned by the telephone service providers that have been funded by the CA 9-1-1 Branch. The CA 9-1-1 Branch Advisor and the PSAP management will review this information together to ensure that the records are accurate, that the services are required, and that the billing is correct.

According to the billing records from the serving telephone company (as entered for this draft), it appears that the CA 9-1-1 Branch is paying for **${num(n.totalLines)}** total telephone lines for ${pkg.cover.psapName || "[PSAP]"}, including **${num(n.trunks911)}** 9-1-1 trunks and **${num(n.alternateAnswer)}** alternate answer line(s)${n.alternateAnswerPsap ? ` (alternate answer PSAP: ${n.alternateAnswerPsap})` : ""}. These network services will be verified during the FOR meeting.

${n.notes ? `## Discussion notes\n\n${n.notes}` : ""}

**Prep note:** If BTN assignment discrepancies are discovered, the ETS database should be corrected via Fiscal Administration Unit processes.
`;
  return section("section_ii", "Section II — Network Review", md);
}

export function renderSectionIII(pkg: ForPackage): RenderedSection {
  const c = pkg.cpe;
  const md = `# Section III — Customer Premise Equipment (CPE) and Maintenance

**PSAP:** ${pkg.cover.psapName || "[PSAP Name]"}  
**Date:** ${pkg.cover.forDate || "[Date]"}

The Customer Premise Equipment (CPE) Review includes equipment funded by the CA 9-1-1 Branch, including associated maintenance. The Advisor and PSAP Manager will review the equipment list and discuss vendor maintenance.

| Field | Value |
| --- | --- |
| CPE contract vendor | ${c.vendor || "[TBD]"} |
| System type deployed | ${c.systemType || "[TBD]"} |
| State-funded 9-1-1 positions | ${num(c.stateFundedPositions)} |
| State MPA contract number | ${c.mpaContract || "[TBD]"} |
| TD-288 tracking | ${c.td288Tracking || "[TBD]"} |
| TD-288 approval date | ${c.td288ApprovalDate || "[TBD]"} |
| System acceptance | ${c.systemAcceptance || "[TBD]"} |
| Expiration of 5-year maintenance | ${c.maint5yrExpiration || "[TBD]"} |

${c.issues ? `## Issues of particular interest\n\n${c.issues}` : "*(Describe any extended maintenance Year-6/7 or residual topics during the meeting.)*"}

*Include TD-288 CPE/Maintenance procurement documents as verification attachments.*
`;
  return section("section_iii", "Section III — CPE and Maintenance", md);
}

export function renderSectionIV(pkg: ForPackage): RenderedSection {
  const o = pkg.ops;
  const asa = o.pctAnswered15s;
  const substandard =
    asa != null && asa < 90
      ? `\n\nThe fact that the ASA is substandard is of significant concern and this issue will be discussed further during the Fiscal and Operational Review (FOR) meeting.\n`
      : "";

  const md = `# Section IV — Operational Performance

**PSAP:** ${pkg.cover.psapName || "[PSAP Name]"}  
**Date:** ${pkg.cover.forDate || "[Date]"}

## Speed of Answer

The current standard for answering calls in California (CA 9-1-1 Operations Manual Chapter I / NENA-aligned practice) is that **at least 90% of 9-1-1 calls should be answered within 15 seconds**.

According to Emergency Call Tracking System (ECaTS) data entered for this draft, this PSAP answered an average of **${asa != null ? `${asa}%` : "___%"}** of 9-1-1 calls within 15 seconds over the past **${num(o.monthsSampled, "xx")}** months.
${substandard}
This agency has answered an average of **${num(o.avgCallsPerMonth, "[XXX]")}** 9-1-1 calls per month over the sample period.

## 24/7 Operation

The current standard for PSAPs funded by the CA 9-1-1 Branch is that they must answer 9-1-1 calls 24 hours a day, 7 days a week. The ECaTS / operational posture indicates that this PSAP ${is24x7Text(o.is24x7)}

## Master Street Address Guide (MSAG) Update Process

The CA 9-1-1 Branch is interested in understanding the process utilized when an inaccuracy is identified in the MSAG database and how that information is communicated to the 9-1-1 County Coordinator for correction.

**County Coordinator contact**
- Name: ${o.countyCoordinatorName || "[TBD]"}
- Phone: ${o.countyCoordinatorPhone || "[TBD]"}
- Email: ${o.countyCoordinatorEmail || "[TBD]"}

## Text to 9-1-1

${text911Text(o.textTo911)}

## Teletypewriter (TTY) Capability

According to current NENA operational standards, PSAP answering equipment should accept TTY calls and call-takers should be trained. NENA standards: https://www.nena.org/page/standards

${o.ttyNotes ? `**Site notes:** ${o.ttyNotes}` : ""}

## Management Information System (MIS / ECaTS)

The CA 9-1-1 Branch contracts for MIS (ECaTS) to monitor call activity. Portal: https://ca.ecats911.com/  
Help Desk: (888) 725-8099 · support@ecats911.com

${o.opsNotes ? `## Additional operational notes\n\n${o.opsNotes}` : ""}
`;
  return section("section_iv", "Section IV — Operational Performance", md);
}

export function renderSectionV(pkg: ForPackage): RenderedSection {
  const n = pkg.ng;
  const md = `# Section V — Next Generation 9-1-1 and Cloud-based CPE

**PSAP:** ${pkg.cover.psapName || "[PSAP Name]"}  
**Date:** ${pkg.cover.forDate || "[Date]"}

Next Generation 9-1-1 (NG 9-1-1) allows for quicker delivery and more accurate routing of 9-1-1 calls, and provides better resiliency and redundancy. NG 9-1-1 equipment is to be installed in all PSAPs within the State of California, enabling transition from legacy CAMA trunks to NENA i3-compliant IP-based call delivery.

Each PSAP will have redundant connections to the Prime Network Service Provider (PNSP) as well as the Regional Network Service Provider (RNSP) — the Next Gen Core Service (NGCS) providers that deliver 9-1-1 calls in the NG environment.

Cloud-based Call Processing Equipment (CPE) is NENA i3 compliant and approved for California PSAPs. Benefits include reduced backroom footprint, integrated text-to-911, mapping integration, and reduced onsite repair presence.

## Discussion checklist (this draft)

- PNSP connectivity discussed: **${n.pnspConnected ? "Yes" : "Pending / No"}**
- RNSP connectivity discussed: **${n.rnspConnected ? "Yes" : "Pending / No"}**
- Cloud CPE options discussed: **${n.cloudCpeDiscussed ? "Yes" : "Pending / No"}**

${n.notes ? `## Site-specific notes\n\n${n.notes}` : ""}
`;
  return section("section_v", "Section V — NG 9-1-1 and Cloud CPE", md);
}

export function renderSectionVI(pkg: ForPackage): RenderedSection {
  const md = `# Section VI — References

**PSAP:** ${pkg.cover.psapName || "[PSAP Name]"}  
**Date:** ${pkg.cover.forDate || "[Date]"}

The Reference section provides links and contacts for additional information regarding 9-1-1 standards, CA 9-1-1 Branch materials, and related organizations. The Advisor will review the reference list with the PSAP.

## Standard references

- CA 9-1-1 Operations Manual (Branch internal / published chapters)
- NENA standards: https://www.nena.org/page/standards
- ECaTS portal: https://ca.ecats911.com/
- California Government Code §§ 53100–53120 (SETNA / emergency telephone systems framework)
- Text-to-911: Government Code § 53112(d)

${pkg.references.extraLinks ? `## Additional links / contacts\n\n${pkg.references.extraLinks}` : ""}
`;
  return section("section_vi", "Section VI — References", md);
}

export function renderSummary(pkg: ForPackage): RenderedSection {
  const five = suggestFiveYearEstimate(pkg);
  const asa = pkg.ops.pctAnswered15s;
  const md = `# Fiscal and Operational Review — Summary

**${pkg.cover.psapName || "[PSAP Name]"}**  
**${pkg.cover.forDate || "[Date]"}**

The California Government Code Sections 53100–53120 authorize the California 9-1-1 Emergency Communications Branch (CA 9-1-1 Branch) to oversee disbursement of funds collected from the State Emergency Telephone Number Account (SETNA) and to oversee the 9-1-1 system for the State of California. Included in Government Code Section 53114.2 is the CA 9-1-1 Branch’s obligation to publish, review, and update technical and operational standards for public agency systems on an ongoing basis. Further, the CA 9-1-1 Branch is to monitor emergency telephone systems to ensure they comply with minimal operational and technical standards as described in Government Code Section 53115e. Therefore, the CA 9-1-1 Branch is providing this review of fiscal and operational policies for the benefit of the Public Safety Answering Point (PSAP) and the State of California.

This review includes a summary of the funding provided by the CA 9-1-1 Branch for the PSAP’s last upgrade and funding provided on a continuing basis for operations and other authorized activities. Additionally, this review addresses performance requirements, CA 9-1-1 Branch funded equipment deployments, and industry standards.

**This Summary provides the PSAP with an overview of the intent and scope of the Fiscal and Operational Review (FOR).**

## Section I — Fiscal Review

The CA 9-1-1 Branch provided **${money(pkg.fiscal.cpeOnlyCost)}** for the last upgrade at ${pkg.cover.psapName || "[PSAP]"} in addition to approximately **${money(pkg.fiscal.ongoingOpsCost)}** for ongoing operations during the past fiscal year. The CA 9-1-1 Branch anticipates providing approximately **${money(five)}** over five years for 9-1-1 service at ${pkg.cover.psapName || "[PSAP]"}.

## Section II — Network Review

According to billing records entered for this draft, the CA 9-1-1 Branch is paying for **${num(pkg.network.totalLines)}** total telephone lines, including **${num(pkg.network.trunks911)}** 9-1-1 trunks and **${num(pkg.network.alternateAnswer)}** alternate answer line(s). These services will be verified during the FOR meeting.

## Section III — Customer Premise Equipment (CPE)

CPE vendor **${pkg.cpe.vendor || "[TBD]"}**, system **${pkg.cpe.systemType || "[TBD]"}**, TD-288 **${pkg.cpe.td288Tracking || "[TBD]"}**. ${pkg.cpe.issues ? `Discussion focus: ${pkg.cpe.issues}` : "Equipment list and maintenance will be reviewed with the PSAP Manager."}

## Section IV — Operational Performance

According to ECaTS data entered for this draft, **${asa != null ? `${asa}%` : "XX%"}** of 9-1-1 calls are answered within 15 seconds at ${pkg.cover.psapName || "[PSAP]"}. The CA 9-1-1 Branch standard is **90% of 9-1-1 calls answered within 15 seconds**.

Per California Government Code section 53112(d), each PSAP shall deploy text-to-911 service capable of accepting SMS and RTT. ${text911Text(pkg.ops.textTo911)}

## Section V — Next Generation 9-1-1 and Cloud-based CPE

NG 9-1-1 and cloud CPE options, including PNSP/RNSP connectivity themes, will be reviewed. PNSP discussed: ${pkg.ng.pnspConnected ? "yes" : "pending"}; RNSP discussed: ${pkg.ng.rnspConnected ? "yes" : "pending"}; cloud CPE discussed: ${pkg.ng.cloudCpeDiscussed ? "yes" : "pending"}.

## Section VI — References

Reference links and contacts are provided for standards, Branch materials, and related organizations.

## Conclusion

This FOR is part of the CA 9-1-1 Branch’s statutory obligation to monitor adherence to standards and is also intended as a review of support provided by the Branch and to strengthen communications with the PSAP.

${pkg.findings.preMeeting ? `## Preliminary findings / issues for discussion\n\n${pkg.findings.preMeeting}` : ""}

*Prep instruction: Summary should be finalized after Sections I–VI are complete. This draft was assembled by FOR Engine ${pkg.meta.version}.*
`;
  return section("summary", "FOR Summary", md);
}

export function renderChecklist(pkg: ForPackage): RenderedSection {
  const lines = pkg.evidence.map(
    (e) => `- [${e.present ? "x" : " "}] ${e.required ? "**[Required]** " : ""}${e.label}`
  );
  const md = `# FOR Prep Checklist

**PSAP:** ${pkg.cover.psapName || "[PSAP Name]"}  
**Date:** ${pkg.cover.forDate || "[Date]"}

${lines.join("\n")}

## Status

- Required evidence complete: **${pkg.evidence.filter((e) => e.required).every((e) => e.present) ? "Yes" : "No"}**
- Generated: ${pkg.meta.generatedAt}
`;
  return section("checklist", "Prep Checklist", md);
}

export function renderFindings(pkg: ForPackage): RenderedSection {
  const md = `# FOR Findings Log (stub)

**PSAP:** ${pkg.cover.psapName || "[PSAP Name]"}  
**Date:** ${pkg.cover.forDate || "[Date]"}

## Pre-meeting / preliminary

${pkg.findings.preMeeting || "_(none entered)_"}

## Post-meeting

${pkg.findings.postMeeting || "_(complete after FOR meeting)_"}
`;
  return section("findings", "Findings Log", md);
}

export function renderAllSections(pkg: ForPackage): RenderedSection[] {
  // Summary last in prep order for writing, but we include cover first then sections then summary for package readability
  return [
    renderCover(pkg),
    renderSectionI(pkg),
    renderSectionII(pkg),
    renderSectionIII(pkg),
    renderSectionIV(pkg),
    renderSectionV(pkg),
    renderSectionVI(pkg),
    renderSummary(pkg),
    renderChecklist(pkg),
    renderFindings(pkg),
  ];
}

export function buildFullMarkdown(pkg: ForPackage): string {
  return renderAllSections(pkg)
    .map((s) => s.markdown)
    .join("\n\n---\n\n");
}

export function buildFullHtmlDocument(pkg: ForPackage): string {
  const sections = renderAllSections(pkg);
  const body = sections
    .map(
      (s) =>
        `<section id="${s.id}" class="for-section"><h1 class="sr-only">${esc(s.title)}</h1>${s.html}</section>`
    )
    .join("\n<hr/>\n");
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8"/>
  <title>FOR — ${esc(pkg.cover.psapName || "Draft")} — ${esc(pkg.cover.forDate || "")}</title>
  <style>
    body { font-family: Georgia, "Times New Roman", serif; max-width: 800px; margin: 2rem auto; padding: 0 1rem; color: #111; line-height: 1.45; }
    h1 { font-size: 1.5rem; margin-top: 1.5rem; }
    h2 { font-size: 1.2rem; margin-top: 1.2rem; }
    h3 { font-size: 1.05rem; }
    table { border-collapse: collapse; width: 100%; margin: 0.75rem 0; }
    td, th { border: 1px solid #ccc; padding: 0.35rem 0.5rem; text-align: left; vertical-align: top; }
    hr { margin: 2rem 0; border: none; border-top: 1px solid #999; }
    .meta { color: #555; font-size: 0.9rem; }
    @media print { hr { break-after: page; } }
  </style>
</head>
<body>
  <p class="meta">Draft FOR package · Engine ${esc(pkg.meta.version)} · Generated ${esc(pkg.meta.generatedAt)} · Decision support only</p>
  ${body}
</body>
</html>`;
}
